name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: apps/web-ui

      - name: Build
        run: npm run build # Change this command based on your build process
        working-directory: apps/web-ui

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main # Change this if you're using a different branch for deployment
          FOLDER: apps/web-ui/dist # Change this to the folder containing your built files
